version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/.github/actions/update-website/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10

